version: '3'
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8123:8123"
    environment:
      - "GIN_MODE=release"

  static-server:
    image: halverneus/static-file-server:latest
    volumes:
      - ./demo-page/:/data:ro
    ports:
      - "8800:8080"
    environment:
      - "FOLDER=/data"

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  minio:
    command: server /data --console-address ":9001"
    image: minio/minio
    restart: unless-stopped
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: topsecret

volumes:
  minio-data:
